1649845049086	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1649859717508	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: true
1649859717508	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649859717511	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1649859717512	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649859718006	Sync.SyncScheduler	DEBUG	Woke from sleep.
1649859718007	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1649859718007	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1649859718007	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649859718318	Sync.Service	DEBUG	User-Agent: Firefox/99.0 (Linux x86_64) FxSync/1.101.0.20220404170724.desktop
1649859718318	Sync.Service	INFO	Starting sync at 2022-04-13 19:51:58 in browser session 4a5b6dwyS9dK
1649859718318	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649859718320	Sync.Status	INFO	Resetting Status.
1649859718320	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1649859718321	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1649859718321	FirefoxAccounts	DEBUG	getOAuthToken enter
1649859718321	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649859718321	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649859718322	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1649859718323	Sync.SyncAuthManager	INFO	Getting sync key
1649859718323	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1649859718323	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1649859718323	FirefoxAccounts	DEBUG	getOAuthToken enter
1649859718323	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649859718323	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649859718323	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1649859718323	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1649859718325	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1649859718326	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1649859718328	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1649859718328	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649859718329	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1649859718329	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1649859718329	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649859718331	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1649859718332	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1649859718333	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1649859718333	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1649859718333	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1649859718333	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1649859718334	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1649859718337	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
