1650027057418	Sync.LogManager	DEBUG	Flushing file log
1650027057427	Sync.LogManager	DEBUG	Log cleanup threshold time: 1649163057427
1650027057437	Sync.LogManager	DEBUG	Done deleting files.
1650027480190	Sync.Service	DEBUG	User-Agent: Firefox/99.0.1 (Linux x86_64) FxSync/1.101.0.20220413030647.desktop
1650027480190	Sync.Service	INFO	Starting sync at 2022-04-15 18:28:00 in browser session 4YeLCZhZTnFu
1650027480190	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1650027480192	Sync.Status	INFO	Resetting Status.
1650027480192	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1650027480192	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1650027480192	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1650027480193	Sync.ErrorHandler	ERROR	Sync encountered an error: Error: Can't sync: Network is offline(resource://services-sync/stages/enginesync.js:59:13) JS Stack trace: sync@enginesync.js:59:13
onNotify@service.js:1351:28
WrappedNotify@util.js:210:32
WrappedLock@util.js:166:27
_lockedSync@service.js:1370:6
sync/<@service.js:1334:18
WrappedCatch@util.js:133:27
sync@service.js:1335:7
1650027480193	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1650027480193	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 8823125 ms.
1650027480193	Sync.SyncScheduler	DEBUG	Next sync in 8823125 ms. (why=client-backoff-schedule)
1650027480194	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1650027480200	Sync.Service	DEBUG	Exception calling anonymous function: Error: Can't sync: Network is offline(resource://services-sync/stages/enginesync.js:59:13) JS Stack trace: sync@enginesync.js:59:13
onNotify@service.js:1351:28
WrappedNotify@util.js:210:32
WrappedLock@util.js:166:27
_lockedSync@service.js:1370:6
sync/<@service.js:1334:18
WrappedCatch@util.js:133:27
sync@service.js:1335:7
